import os
import streamlit as st
import pandas as pd
import geopandas as gpd
import folium
import plotly.express as px
from branca.element import MacroElement, Template
from map_utils import create_geoai_map
from audit_logger import log_event
from streamlit_folium import st_folium
from datetime import datetime

st.set_page_config(
    page_title="GeoAI Surveillance Dashboard",
    layout="wide"
)

st.title("GeoAI Surveillance Dashboard Prototype")
st.caption("Privacy-preserving district-level COVID-19 outbreak risk monitoring system")

st.caption(f"Last Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} UTC")

col1, col2, col3 = st.columns(3)

with col1:
    st.success("System Status: Operational")

with col2:
    st.info("API Gateway: Healthy")

with col3:
    st.warning("Audit Logging: Active")

@st.cache_data
def load_data():
    df = pd.read_csv("data/demo_geoai_surveillance_outputs.csv")
    df["Date"] = pd.to_datetime(
        df["Year"].astype(str) + "-" + df["Month"].astype(str) + "-01"
    )
    return df


df = load_data()


# --------------------------------
# Operational Summary Metrics
# --------------------------------

latest_df = (
    df.sort_values(["Year", "Month"])
      .groupby("adm2_name")
      .tail(1)
      .copy()
)

high_risk_count = (latest_df["Risk_Level"] == "High Risk").sum()
avg_risk_score = latest_df["Outbreak_Probability"].mean()
avg_risk_score_pct = avg_risk_score * 100

try:
    hotspot_gdf = gpd.read_file("data/demo_geoai_spatial_intelligence.geojson")

    if "Hotspot_Class" in hotspot_gdf.columns:
        active_hotspots = (hotspot_gdf["Hotspot_Class"] == "Hotspot").sum()

    elif "GiZScore" in hotspot_gdf.columns and "GiPValue" in hotspot_gdf.columns:
        active_hotspots = (
            (hotspot_gdf["GiPValue"].astype(float) <= 0.05)
            & (hotspot_gdf["GiZScore"].astype(float) > 1.96)
        ).sum()

    else:
        active_hotspots = "N/A"

except Exception:
    active_hotspots = "N/A"

try:
    audit_log = pd.read_csv("logs/audit_log.csv")
    governance_events = len(audit_log)
except FileNotFoundError:
    governance_events = 0

latest_data_period = latest_df["Date"].max().strftime("%b %Y")

m1, m2, m3, m4, m5 = st.columns(5)

with m1:
    st.metric("Top Risk Districts", 10)
    st.caption(
        "Operational ranking of the ten districts with the highest current predicted outbreak probabilities."
    )

with m2:
    st.metric("Average Risk Score", f"{avg_risk_score_pct:.2f}%")
    st.caption(
        "Mean predicted outbreak probability across the latest district records. "
        "Displayed as a percentage; higher values indicate greater average predicted outbreak risk."
    )

with m3:
    st.metric("Active Hotspots", active_hotspots)
    st.caption(
        "Number of districts identified as spatial hotspots using hotspot-intelligence outputs. "
        "This is different from the Top Risk Districts ranking."
    )

with m4:
    st.metric("Governance Events Logged", governance_events)
    st.caption(
        "Number of recorded governance and audit-log events generated by dashboard and API activity."
    )

with m5:
    st.metric("Latest Data", latest_data_period)
    st.caption(
        "Most recent surveillance period represented in the dashboard."
    )

st.sidebar.header("District Selection")

st.sidebar.markdown("""

### Dashboard Navigation

Use this dashboard to explore:

* District-level outbreak-risk information
* Spatial hotspot intelligence
* Explainable AI insights
* Model performance summaries
* Environmental and epidemiological trends
* Governance and privacy controls

Select a county and district below to update all charts, indicators, and maps.
""")

# --------------------------------

# County Selection

# --------------------------------

counties = sorted(df["adm1_name"].dropna().unique())

selected_county = st.sidebar.selectbox(
"Select County",
counties
)

# --------------------------------

# District Selection (filtered by county)

# --------------------------------

county_districts = sorted(
df.loc[
df["adm1_name"] == selected_county,
"adm2_name"
]
.dropna()
.unique()
)

selected_district = st.sidebar.selectbox(
"Select District",
county_districts
)

top_risk = (
    latest_df
      .sort_values(by="Outbreak_Probability", ascending=False)
      .head(10)
      .copy()
)

st.subheader("Top Risk Districts")

st.caption(
    "This table ranks the ten districts with the highest current predicted outbreak probabilities. "
    "It supports surveillance prioritisation and should not be interpreted as identical to the High-, "
    "Moderate-, and Low-Risk categories shown on the risk-classification map."
)

top_risk_display = top_risk.rename(
    columns={
        "adm2_name": "District",
        "adm1_name": "County",
        "Outbreak_Probability": "Predicted Outbreak Probability (0–1)",
        "Risk_Level": "Surveillance Risk Level"
    }
)[[
    "District",
    "County",
    "Predicted Outbreak Probability (0–1)",
    "Surveillance Risk Level"
]]

top_risk_display["Predicted Outbreak Probability (%)"] = (
    top_risk_display["Predicted Outbreak Probability (0–1)"] * 100
).round(2)

st.dataframe(
    top_risk_display[
        [
            "District",
            "County",
            "Predicted Outbreak Probability (0–1)",
            "Predicted Outbreak Probability (%)",
            "Surveillance Risk Level"
        ]
    ],
    width="stretch"
)

log_event(
    user_role="analyst",
    action="district_selected",
    district=selected_district
)

start_period = df["Date"].min().strftime("%B %Y")
end_period = df["Date"].max().strftime("%B %Y")

st.caption(f"Dataset Coverage Period: {start_period} – {end_period}")

district_df = df[df["adm2_name"] == selected_district].copy()

latest_record = district_df.sort_values(
    ["Year", "Month"]
).iloc[-1]


# -----------------------------
# KPI Cards
# -----------------------------
col1, col2, col3, col4 = st.columns(4)

col1.metric("District", latest_record["adm2_name"])
col2.metric("County", latest_record["adm1_name"])
col3.metric("Outbreak Probability", f"{latest_record['Outbreak_Probability'] * 100:.2f}%")
col4.metric("Risk Level", latest_record["Risk_Level"])


with st.expander("How are risk levels interpreted?"):

    st.markdown("""
### GeoAI Risk Outputs

The dashboard presents GeoAI risk outputs in three complementary ways:

- **Predicted Outbreak Probability**
  - A model-generated probability ranging from 0 to 1.
  - Higher values indicate greater predicted outbreak risk.

- **Surveillance Risk Level**
  - Districts are grouped into **Low**, **Moderate**, and **High Risk** categories using quantile-based classification of the predicted outbreak probabilities.
  - These categories represent relative levels of predicted risk across districts rather than fixed epidemiological thresholds.
  - The resulting classifications are displayed on the GeoAI Risk Classification Map.

- **Top Risk Districts**
  - An operational ranking of districts with the highest current predicted outbreak probabilities.
  - This ranking supports surveillance prioritisation and resource allocation.

### Understanding the Difference

The **GeoAI Risk Classification Map** groups all districts into Low-, Moderate-, and High-Risk categories based on their relative predicted outbreak risk.

The **Top Risk Districts** table ranks districts according to their current predicted outbreak probabilities and displays only the highest-ranked districts.

Therefore, a district may appear in the Top Risk Districts table because it ranks among the highest current probabilities, while the GeoAI Risk Classification Map provides a broader categorisation of risk across all districts.

### Operational Interpretation

#### High Risk
- Immediate surveillance attention recommended.
- Review outbreak indicators and hotspot intelligence.
- Consider escalation and resource mobilisation where appropriate.

#### Moderate Risk
- Enhanced monitoring recommended.
- Review trend direction and recent surveillance indicators.
- Prepare escalation if risk increases.

#### Low Risk
- Routine surveillance recommended.
- Continue periodic monitoring and review.
""")

# --------------------------------
# Recommended Actions
# --------------------------------

st.subheader("Recommended Actions")

selected_risk_level = latest_record["Risk_Level"]

if selected_risk_level == "High Risk":
    st.error("""
    **High Risk – Recommended Actions**

    - Initiate immediate surveillance review.
    - Prioritise field investigation and case verification.
    - Increase monitoring frequency.
    - Review hotspot intelligence and recent case trends.
    - Prepare targeted resource allocation if risk persists.
    """)

elif selected_risk_level == "Moderate Risk":
    st.warning("""
    **Moderate Risk – Recommended Actions**

    - Continue enhanced surveillance monitoring.
    - Review district trend direction and hotspot indicators.
    - Monitor recent case activity and incidence changes.
    - Prepare escalation if risk increases.
    """)

else:
    st.success("""
    **Low Risk – Recommended Actions**

    - Continue routine surveillance.
    - Maintain periodic monitoring.
    - Review trends if new cases or hotspot signals emerge.
    """)

st.caption(
    f"Current classification based on GeoAI prediction: "
    f"{latest_record['Risk_Level']} "
    f"(Predicted outbreak probability = "
    f"{latest_record['Outbreak_Probability']*100:.2f}%)."
)

latest_two = district_df.sort_values("Date").tail(2)

if len(latest_two) == 2:
    previous = latest_two.iloc[0]["Outbreak_Probability"]
    current = latest_two.iloc[1]["Outbreak_Probability"]

    if current > previous * 1.05:
        trend_status = "Increasing"
    elif current < previous * 0.95:
        trend_status = "Decreasing"
    else:
        trend_status = "Stable"

    trend_col1, trend_col2 = st.columns(2)

    with trend_col1:
        st.metric(
            "Current Outbreak Probability",
            f"{latest_record['Outbreak_Probability']*100:.2f}%"
        )

    with trend_col2:
        st.metric(
            "Trend Direction",
            trend_status
        )

# -----------------------------
# Trend chart
# -----------------------------
st.subheader("Temporal Outbreak Probability Trend")

with st.expander("About this trend chart"):
    st.markdown("""
    This chart shows how predicted outbreak probability changes over time
    for the selected district, supporting trend monitoring and early warning.
    """)

trend_fig = px.line(
    district_df.sort_values("Date"),
    x="Date",
    y="Outbreak_Probability",
    markers=True,
    title=f"Outbreak Probability Trend: {selected_district}"
)

trend_fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Predicted Outbreak Probability"
)

st.plotly_chart(trend_fig, width="stretch")

# --------------------------------
# Operational Alert Panel
# --------------------------------

st.subheader("Operational Alert Summary")

st.markdown("""
This section highlights districts currently exhibiting elevated outbreak risk.
The alerts support prioritisation of surveillance activities and resource allocation.
""")

high_risk_count = latest_df[
    latest_df["Risk_Level"] == "High Risk"
].shape[0]

moderate_risk_count = latest_df[
    latest_df["Risk_Level"] == "Moderate Risk"
].shape[0]

if high_risk_count > 0:
    st.error(
        f"{high_risk_count} district(s) are currently ranked within the highest outbreak-probability group."
    )

if moderate_risk_count > 0:
    st.warning(
        f"{moderate_risk_count} district(s) are currently flagged for enhanced surveillance monitoring."
    )

if high_risk_count == 0 and moderate_risk_count == 0:
    st.success("No elevated district-level outbreak risk detected.")

st.info(
    "The Top Risk Districts table provides a ranking based on predicted outbreak probability and should not be interpreted as equivalent to the High-, Moderate-, and Low-Risk classifications displayed on the GeoAI risk-classification map."
)


# --------------------------------
# Interactive GeoAI Map
# --------------------------------
st.subheader("Operational GeoAI Spatial Intelligence Map")

with st.expander("About this map"):
    st.markdown("""
    This interactive map displays district-level outbreak-risk classifications,
    hotspot intelligence, and spatial surveillance information. Users can explore
    geographic patterns of predicted outbreak risk and identify locations requiring
    enhanced surveillance attention.
    """)

geoai_map = create_geoai_map()

legend_template = """
{% macro html(this, kwargs) %}
<div style="
    position: absolute;
    bottom: 40px;
    left: 40px;
    width: 190px;
    background-color: white;
    border: 2px solid grey;
    z-index: 9999;
    font-size: 14px;
    padding: 10px;
    border-radius: 5px;
">
<b>District Risk Classification</b><br>
<small>Predicted outbreak-risk category</small><br><br>
<span style="background:#66c2a5;width:12px;height:12px;display:inline-block;margin-right:8px;"></span>Low Risk<br>
<span style="background:#f6c85f;width:12px;height:12px;display:inline-block;margin-right:8px;"></span>Moderate Risk<br>
<span style="background:#d73027;width:12px;height:12px;display:inline-block;margin-right:8px;"></span>High Risk
</div>
{% endmacro %}
"""

legend = MacroElement()
legend._template = Template(legend_template)
geoai_map.get_root().add_child(legend)

st_folium(
    geoai_map,
    height=850,
    use_container_width=True
)


# --------------------------------
# Environmental & Epidemiological Trend Tabs
# --------------------------------

st.subheader("Environmental and Epidemiological Trend")

with st.expander("About environmental and epidemiological trends"):
    st.markdown("""
    This section presents epidemiological indicators alongside environmental
    variables to support interpretation of potential drivers of outbreak risk.
    """)

env_df = district_df.rename(
    columns={
        "COUNT_OBJECTID": "Reported Cases",
        "Incidence_100k": "Incidence per 100k",
        "Rainfall_mm": "Rainfall (mm)",
        "Temperature_C": "Temperature (°C)"
    }
).sort_values("Date")

tab1, tab2, tab3 = st.tabs(
    [
        "Epidemiological Indicators",
        "Environmental Indicators",
        "Normalized Comparison"
    ]
)

with tab1:
    epi_fig = px.line(
        env_df,
        x="Date",
        y=["Reported Cases", "Incidence per 100k"],
        markers=True,
        title=f"Epidemiological Trend: {selected_district}",
        color_discrete_map={
            "Reported Cases": "#E15759",
            "Incidence per 100k": "#59A14F"
        }
    )

    epi_fig.update_layout(
        xaxis_title="Date",
        yaxis_title="Value",
        legend_title="Indicator",
        template="plotly_white",
        hovermode="x unified"
    )

    st.plotly_chart(epi_fig, width="stretch")


with tab2:
    env_only_fig = px.line(
        env_df,
        x="Date",
        y=["Rainfall (mm)", "Temperature (°C)"],
        markers=True,
        title=f"Environmental Trend: {selected_district}",
        color_discrete_map={
            "Rainfall (mm)": "#4E79A7",
            "Temperature (°C)": "#F28E2B"
        }
    )

    env_only_fig.update_layout(
        xaxis_title="Date",
        yaxis_title="Value",
        legend_title="Indicator",
        template="plotly_white",
        hovermode="x unified"
    )

    st.plotly_chart(env_only_fig, width="stretch")


with tab3:
    normalized_df = env_df.copy()

    indicators = [
        "Reported Cases",
        "Incidence per 100k",
        "Rainfall (mm)",
        "Temperature (°C)"
    ]

    for col in indicators:
        min_val = normalized_df[col].min()
        max_val = normalized_df[col].max()

        if max_val != min_val:
            normalized_df[col] = (
                (normalized_df[col] - min_val) /
                (max_val - min_val)
            )
        else:
            normalized_df[col] = 0

    norm_fig = px.line(
        normalized_df,
        x="Date",
        y=indicators,
        markers=True,
        title=f"Normalized Indicator Comparison: {selected_district}",
        color_discrete_map={
            "Reported Cases": "#E15759",
            "Incidence per 100k": "#59A14F",
            "Rainfall (mm)": "#4E79A7",
            "Temperature (°C)": "#F28E2B"
        }
    )

    norm_fig.update_layout(
        xaxis_title="Date",
        yaxis_title="Normalized Value (0–1)",
        legend_title="Indicator",
        template="plotly_white",
        hovermode="x unified"
    )

    norm_fig.update_traces(
        line=dict(width=3),
        selector=dict(name="Reported Cases")
    )

    norm_fig.update_traces(
        line=dict(width=2, dash="dash"),
        selector=dict(name="Incidence per 100k")
    )

    st.plotly_chart(norm_fig, width="stretch")


# --------------------------------
# Explainable GeoAI Intelligence
# --------------------------------
st.subheader("Explainable GeoAI Intelligence")

with st.expander("About explainable GeoAI intelligence"):
    st.markdown("""
    This section explains why districts are classified as higher or lower outbreak risk.

    The dashboard identifies the main factors influencing outbreak predictions,
    including recent disease activity, population characteristics, and environmental conditions.

    These explanations support transparency and help users understand the reasons
    behind GeoAI-generated predictions.
    """)

col1, col2 = st.columns(2)

if os.path.exists("figures/xgboost_shap_summary_plot.png"):
    with col1:
        st.image(
            "figures/xgboost_shap_summary_plot.png",
            caption="Explanation of key factors influencing outbreak-risk predictions",
            use_container_width=True
        )

if os.path.exists("figures/xgboost_feature_importance.png"):
    with col2:
        st.image(
            "figures/xgboost_feature_importance.png",
            caption="Key Drivers of Outbreak Risk",
            use_container_width=True
        )

st.info("""
Interpretation: The dashboard identifies the main factors associated with predicted outbreak risk.
Recent case trends, population density, rainfall, and temperature help explain why some districts
are classified as higher or lower risk.
""")


# --------------------------------
# Model Confidence and Validation
# --------------------------------
st.subheader("Model Confidence and Validation")

model_results = pd.read_csv("data/demo_final_geoai_model_comparison.csv")

model_results_display = model_results.rename(
    columns={
        "ROC_AUC": "Overall Prediction Performance (ROC-AUC)",
        "Precision": "Accuracy of High-Risk Alerts (Precision)",
        "Recall": "Ability to Detect Outbreaks (Recall)",
        "F1_Score": "Overall Detection Balance (F1-Score)"
    }
)

with st.expander("About model confidence and validation"):
    st.markdown("""
    This section presents the performance of the evaluated prediction models.

    The results demonstrate how accurately the GeoAI framework identifies
    districts at elevated outbreak risk and provide evidence supporting
    the reliability of the surveillance system.
    """)

st.dataframe(
    model_results_display,
    use_container_width=True
)

best_model = model_results.sort_values(
    by=["ROC_AUC", "F1_Score"],
    ascending=False
).iloc[0]

st.success(
    f"Best performing model: {best_model['Model']} "
    f"with strong overall prediction performance and balanced outbreak-detection capability."
)

st.caption("""
Metric guide: Overall Prediction Performance shows how well the model separates higher-risk
from lower-risk districts. Accuracy of High-Risk Alerts indicates how reliable high-risk warnings are.
Ability to Detect Outbreaks shows how well the model identifies outbreak-risk cases.
Overall Detection Balance combines alert reliability and outbreak detection.
""")

st.caption("""
Note: Model confidence is represented through validation metrics such as ROC-AUC,
Precision, Recall, and F1-Score. A district-level uncertainty or confidence interval
was not estimated in this prototype and is recommended for future enhancement.
""")


# -----------------------------
# Risk Level Distribution
# -----------------------------
st.subheader("Risk Level Distribution")

with st.expander("About risk level distribution"):
    st.markdown("""
    This summary displays the current distribution of district outbreak-risk
    classifications across Liberia.
    """)

latest_df = (
    df.sort_values(["Year", "Month"])
      .groupby("adm2_name")
      .tail(1)
)

risk_counts = latest_df["Risk_Level"].value_counts().reset_index()
risk_counts.columns = ["Risk Level", "District Count"]

risk_fig = px.bar(
    risk_counts,
    x="Risk Level",
    y="District Count",
    title="Latest District Risk Classification Summary"
)

risk_fig.update_layout(
    xaxis_title="Risk Level",
    yaxis_title="Number of Districts"
)

st.plotly_chart(risk_fig, width="stretch")


# --------------------------------
# Map and Figure Gallery
# --------------------------------
st.subheader("Analytical Map Outputs")

with st.expander("About analytical map outputs"):
    st.markdown("""
    This gallery provides access to spatial and epidemiological maps generated
    during analysis. The maps support interpretation of disease patterns,
    environmental conditions, hotspot activity, and GeoAI predictions.
    """)

map_files = {
    "Study Area / Administrative Reference Map": "figures/maps/Study Area - Administrative Reference Map.png",
    "GeoAI-Predicted Outbreak Probability": "figures/maps/GeoAI Outbreak Probability Map.png",
    "GeoAI-Based Risk Classification": "figures/maps/GeoAI Risk Classification Map.png",
    "GeoAI-Derived Spatial Hotspot Intelligence": "figures/maps/GEOAI HOTSPOT MAP.png",
    "Local Moran's I Cluster Analysis": "figures/maps/Local Moran’s I Cluster_Outlier Map.png",
    "Traditional Getis-Ord Gi* Hotspot Analysis": "figures/maps/Traditional Hotspot Analysis Map (Getis-Ord Gi).png",
    "Temperature Distribution": "figures/maps/Temperature Distribution Map.png",
    "Rainfall Distribution": "figures/maps/Rainfall Distribution Map.png",
    "Reported COVID-19 Cases": "figures/maps/COVID-19 Case Count Map.png",
    "Cumulative COVID-19 Incidence": "figures/maps/Cumulative Incidence Map.png",
    "Population Density (2022)": "figures/maps/population_density_2022.png",
}

available_maps = {
    name: path for name, path in map_files.items()
    if os.path.exists(path)
}

if available_maps:
    selected_map = st.selectbox(
        "Select analytical map output",
        list(available_maps.keys())
    )

    st.image(
        available_maps[selected_map],
        caption=selected_map,
        use_container_width=True
    )
else:
    st.warning("No map images found. Check the file names inside figures/maps.")


# --------------------------------
# Data Table: Aggregated Surveillance Data
# --------------------------------

st.subheader("Aggregated District-Level Surveillance Data")

with st.expander("About this surveillance data table"):
    st.markdown("""
    This table presents privacy-preserving, district-level surveillance records
    used by the GeoAI framework. No personally identifiable information is displayed.

    Predicted outbreak probability values range from 0 to 1, where higher values
    indicate greater predicted outbreak risk.
    """)

display_df = district_df[
    [
        "adm2_pcode",
        "adm2_name",
        "adm1_name",
        "Year",
        "Month",
        "COUNT_OBJECTID",
        "Incidence_100k",
        "Rainfall_mm",
        "Temperature_C",
        "Outbreak_Probability",
        "Risk_Level"
    ]
].sort_values(["Year", "Month"])

# Rename fields for operational readability
display_df = display_df.rename(
    columns={
        "adm2_pcode": "District Code",
        "adm2_name": "District",
        "adm1_name": "County",
        "COUNT_OBJECTID": "Reported Cases",
        "Incidence_100k": "Incidence per 100k",
        "Rainfall_mm": "Rainfall (mm)",
        "Temperature_C": "Temperature (°C)",
        "Outbreak_Probability": "Predicted Outbreak Probability (0–1)",
        "Risk_Level": "Surveillance Risk Level"
    }
)

# Optional formatting
display_df["Predicted Outbreak Probability (0–1)"] = (
    display_df["Predicted Outbreak Probability (0–1)"]
    .astype(float)
    .apply(lambda x: f"{x:.6f}")
)

display_df["Incidence per 100k"] = (
    display_df["Incidence per 100k"]
    .astype(float)
    .apply(lambda x: f"{x:.2f}")
)

display_df["Rainfall (mm)"] = (
    display_df["Rainfall (mm)"]
    .astype(float)
    .apply(lambda x: f"{x:.2f}")
)

display_df["Temperature (°C)"] = (
    display_df["Temperature (°C)"]
    .astype(float)
    .apply(lambda x: f"{x:.2f}")
)

st.dataframe(
    display_df,
    width="stretch"
)


# --------------------------------
# Scheduled Refresh Simulation
# --------------------------------

from refresh_simulator import simulate_refresh

st.subheader("Scheduled Refresh Simulation")

with st.expander("About scheduled refresh simulation"):
    st.markdown("""
    This section simulates an operational data refresh workflow. In a production
    environment, this process would be scheduled to ingest updated surveillance
    records, validate aggregated district-level data, refresh model outputs, and
    update the dashboard.
    """)

if st.button("Run Simulated Data Refresh"):
    refresh_result = simulate_refresh()

    st.success(refresh_result["message"])
    st.code(refresh_result["backup_file"])
    

# --------------------------------
# Governance and Privacy Controls
# --------------------------------
st.subheader("Governance and Privacy Controls")

with st.expander("About governance and privacy controls"):
    st.markdown("""
    This section summarises the governance and privacy safeguards implemented
    within the surveillance system to support secure, transparent, and accountable use.
    """)

st.success("District-level aggregated surveillance data only")

st.info("""
No personally identifiable information (PII) is stored, displayed,
or transmitted within this GeoAI prototype.
""")

st.markdown("""
Security and governance controls implemented or represented in this prototype include:

- JWT authentication
- Role-Based Access Control (RBAC)
- Audit logging
- Secure API mediation
- Aggregated surveillance analytics
- Privacy-preserving spatial intelligence
- Explainable GeoAI outputs
""")